### ISSUE TITLE
Crossed out battery symbol

### ISSUE THREAD

**Issue by JoghurtConnaisseur** [jezs00/pycasso#46]
I’m getting this symbol on my display. What does it mean? It’s a crossed out battery symbol. My setup is using pijuice and auto power off after completion.

![image](https://user-images.githubusercontent.com/96706991/217461713-66706e01-ff31-468c-9631-98d14502fc8b.jpg)

**Comment by jezs00** [comment]
It's supposed to mean that pijuice class isn't loading properly and applying battery indicator, however it's probably an error seeing as I have the same. Will look into it. You can disable icons in .config if you like.

**Comment by jezs00** [comment]
Issue was with range assignment, using - instead of ,

Appears to be working now, will create new release with this fix and the previous in it.
