### ISSUE TITLE
Don't use rc.local for startup

### ISSUE THREAD

**Issue by recrudesce** [jezs00/pycasso#47]
See https://raspberrypi.stackexchange.com/questions/117729/rc-local-not-able-to-execute-python-script-with-network-code

The service that's being created is using rc.local, which has been causing me some issues lately where it's starting the script before the network is up on the Pi, and resulting in errors regarding not being able to connect to my local Stable Diffusion service.

Changing `After=rc-local.service` to `After=network.target` in the systemd service fixes it :)

**Comment by jezs00** [comment]
Sounds good to me!
