### ISSUE TITLE
New: Text read from file rather than image prompt

### ISSUE THREAD

**Issue by djxie2019** [jezs00/pycasso#58]
Would be great if there was an option to pull the text displayed from a file instead? Use case is using GPT to write descriptions.

**Comment by jezs00** [comment]
Hey mate,

Can you be a bit more specific on the use case? The text displayed is
intrinsically linked to the image requested, so as far as I can picture it,
having a separate text file to draw text would be complicated to link up to
the request.

The only way I can see this working is either using GPT to write the
prompts pre-request, or implementing a GPT API in the application itself.

**Comment by djxie2019** [comment]
Sorry I could have been clearer.

Upon boot I have a script that pulls a subjects.txt file from a Home Assistant instance prior to running Pycasso, which dynamically generates the prompt based on the weather, time of day and season. For example, full moon shown in the image if it's a full moon, or browning/bare trees in fall/autumn, raining if raining.

I want to also grab a dynamically generated text descriptor from Home Assistant to display underneath the image, that describes current conditions in more granular detail, ie. the temperature, forecast or any noteworthy happenings in the smart home that day. Home Assistant already has ChatGPT built in to generate these.

Would also be good to have more control of the text, ie. wrapping. Love what you've created btw.

**Comment by jezs00** [comment]
Great idea. Yes, that's definitely possible. It will require config
updates, new file parser and appropriate insertion into the main program.
Should unit test it too. I'll try and update it at some point.

**Comment by jezs00** [comment]
Should have the option to set override_text and override_path now in release 1.2.8.
