### ISSUE TITLE
TFT-Screen

### ISSUE THREAD

**Issue by soldatino13** [jezs00/pycasso#60]
would this also work with a PiTFT 3.5" screen? [https://www.adafruit.com/product/2097](url)
If so, what would need to be done? Because nothing is displayed at the moment

**Comment by jezs00** [comment]
pycasso implements [omni-epd](https://github.com/robweber/omni-epd) , which does not appear to support this screen and probably won't in the future as it's not an EPD. You can feel free to post an issue there if you'd like to request that functionality there, but I don't think it's in scope of that project either.

It might not be too hard to retrofit a solution into pycasso to display this from possibly the mockepd generated image, but I will close this issue as that's out of scope of this project.
